apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server
  labels:
    app: socket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
        - name: netcat
          image: my-nc:latest
          imagePullPolicy: Never
          command: ['sleep']
          args: ['infinity']
          ports:
            - containerPort: 19998

---
apiVersion: v1
kind: Service
metadata:
  name: socket-server
  labels:
    app: socket-server
spec:
  #  type: NodePort
  type: LoadBalancer
  selector:
    app: socket-server
  ports:
    - protocol: TCP
      port: 19998
      targetPort: 19998